# Generated by Django 3.0.8 on 2020-07-20 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(default='na', max_length=256)),
                ('phn_num', models.CharField(default='', max_length=15)),
                ('pin_code', models.CharField(default='', max_length=8)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
