# Generated by Django 3.0.8 on 2020-07-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='iid',
        ),
    ]
