# Generated by Django 3.0.8 on 2020-07-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_auto_20200720_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='name',
            field=models.CharField(default='last_attemp', max_length=256),
        ),
    ]
