# Generated by Django 3.0.8 on 2020-07-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_auto_20200721_1052'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='name',
            field=models.CharField(default='sanku', max_length=256),
        ),
    ]
