# Generated by Django 3.0.8 on 2020-07-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0005_auto_20200721_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='name',
            field=models.CharField(default='vaali', max_length=256),
        ),
    ]
